### ISSUE TITLE
Preview format

### ISSUE THREAD

**Issue by superdyzio** [FrancescoBorzi/ngx-duration-picker#12]
I understand that current format is a default, ISO-consistent format, but it would be nice to have possibility to pass some text (probably translatable) as preview, so it can show labels like 

> 5 hours 0 minutes 15 seconds

Thanks for that lib, regards!

**Comment by ShinDarth** [comment]
@superdyzio I don't have enough time to work on those suggestions now, but PRs are welcome. However I think it would be better to split one suggestion per issue.

**Comment by superdyzio** [comment]
@ShinDarth ok, later I will divide my ideas into separate issues and in free time I'll start working on them - this issue will be related to preview / output format - as stands in title

**Comment by superdyzio** [comment]
resolved in #21
