### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by superdyzio** [FrancescoBorzi/ngx-duration-picker#14]
Currently only possible output format is default ISO. It would be nice to be able to configure that and get number or custom string as output.
It can go even further and since duration picker default use is to determine duration of some event / annotation etc. it would be great to pass startTime to ngx-duration-picker and get endTime as Date or moment object.

I'll try to work on that later.

**Comment by superdyzio** [comment]
I'm starting working on that. I'll add `outputFormat: string` option and possible values will be:
```
- ISO (default)
- timestamp (milliseconds, convenient when adding duration to some startTime)
- seconds (as above, but without additional zeros at the end; durationPicker's lowest unit)
- any other string (treated as string for previewFormat option)
```

@FrancescoBorzi are you ok with that?

**Comment by FrancescoBorzi** [comment]
@superdyzio as long as the default behaviour is not affected by this change, and it does not alter any other existing configuration, I'm absolutely fine with that!

**Comment by superdyzio** [comment]
@FrancescoBorzi please check #46

**Comment by superdyzio** [comment]
#46 merged- > closing issue

**Comment by SpeCT** [comment]
cool stuff. thank you guys 👍 
@FrancescoBorzi any plans to publish this to npm?

**Comment by FrancescoBorzi** [comment]
@SpeCT done: 3.2.0

**Comment by FrancescoBorzi** [comment]
@SpeCT you can give us a Star if you like it :)

and good job @superdyzio
