### ISSUE TITLE
Configurable labels with units

### ISSUE THREAD

**Issue by superdyzio** [FrancescoBorzi/ngx-duration-picker#15]
Currently there is option to show letters above unit controls but it would be nice to be able to put there some custom labels.

I'll work on that later.

**Comment by MarAvFe** [comment]
Are you still working on that? I'm interested. If you let it die, I'll take it

**Comment by MarAvFe** [comment]
This is because I wan't i18n. But to avoid words making the vertical alignment weird, my idea is to add a property to modify the letters shown, and add a property to add titles to the letters, to hover the whole word for the user.

**Comment by FrancescoBorzi** [comment]
@MarAvFe I'm not letting this "die", you are free to add new features by sending a PR.

Just make sure the new features are disabled by default so we don't add breaking changes.

**Comment by MarAvFe** [comment]
Oh no, i meant @superdyzio who said he'd work on it. I'll create a PR tomorrow then!

**Comment by superdyzio** [comment]
@FrancescoBorzi please review #105
