### ISSUE TITLE
The labels are not working

### ISSUE THREAD

**Issue by megametres** [FrancescoBorzi/ngx-duration-picker#324]
Hi, 
You have a cool package but the labels are not working...
![image](https://user-images.githubusercontent.com/2496407/97186325-841d6c80-1777-11eb-8d5e-91c9d70abee2.png)

I suppose that the unitSteps are not working either: take a look at augury's config on your component: ( Not all the config are there... )
![image](https://user-images.githubusercontent.com/2496407/97186897-453be680-1778-11eb-8ece-b6e16cdbe203.png)

**Comment by megametres** [comment]
I tried your localdev setup and it works in it. So it seems that there that the issue is in the packaged version. ( If I add "ngx-duration-picker": "^3.2.0" in your repo instead of doing `ng build ngx-duration-picker --watch` the labels are not working)

**Comment by FrancescoBorzi** [comment]
@megametres thanks for your feedback. Have you tried packaging the latest revision and see if that works?

**Comment by megametres** [comment]
Yes, I just figured that out, the labels are not in the 3.2.0 version... I'll do that! thanks for the quick reply!

**Comment by PpesR** [comment]
> @megametres thanks for your feedback. Have you tried packaging the latest revision and see if that works?

@FrancescoBorzi 
Could you release the latest version so it would come out of the box?

**Comment by FrancescoBorzi** [comment]
@PpesR done! 3.3.0 is out

**Comment by FrancescoBorzi** [comment]
@PpesR FYI: I published 3.3.1 to solve an issue with Ivy compatibility

**Comment by PpesR** [comment]
Thanks, much appreciated!
