### ISSUE TITLE
Step increment / decrement for each time unit

### ISSUE THREAD

**Issue by AmmoTrio** [FrancescoBorzi/ngx-duration-picker#88]
It would be nice to provide the component with step value on each time unit increment / decrement.
For example, in options, pass:
options = {
 ...,
 hourStep: 10,
 minuteStep: 5,
...
}

So, when the user click on Up / Down arrows, 
update the time unit value according to time step value

**Comment by FrancescoBorzi** [comment]
@AmmoTrio nice idea, feel free to send a PR to implement this feature

**Comment by superdyzio** [comment]
@AmmoTrio are you working on that?

**Comment by AmmoTrio** [comment]
No @superdyzio sorry.

**Comment by superdyzio** [comment]
Ok, no problem - it'll probably take me some time (like previous reported issues) but I'll do it 😄

**Comment by superdyzio** [comment]
closed with #144
